baseURL = "https://guangchang.tech"
languageCode = "zh-hans"
defaultContentLanguage = "en"
title = "spider.nns"
theme="hermit"
pygmentsCodefences  = true
pygmentsUseClasses  = true
themeColor = "#494f5c"
homeSubtitle = "技术不存在莫名其妙"
[menu]

  [[menu.main]]
    name = "文章"
    url = "posts/"
    weight = 10

  [[menu.main]]
    name = "标签"
    url = "tags/"
    weight = 10

  [[menu.main]]
    name = "关于"
    url = "about/"
    weight = 20
